// import { authClient } from "@/lib/auth-client";
// import { headers } from "next/headers";

const seededUsers = [
  {
    name: "Archibaldo Kryszka",
    email: "akryszka0@dell.com",
    image: "http://dummyimage.com/199x100.png/5fa2dd/ffffff",
    password: "uM7#K(5Bo7",
  },
  {
    name: "Carole Sneddon",
    email: "csneddon1@japanpost.jp",
    image: "http://dummyimage.com/224x100.png/5fa2dd/ffffff",
    password: "jB2=EC45d@/",
  },
  {
    name: "Julieta Infante",
    email: "jinfante2@mac.com",
    image: "http://dummyimage.com/195x100.png/dddddd/000000",
    password: "kV9*~@Zx<RSqCu$Y",
  },
  {
    name: "Dimitry Poore",
    email: "dpoore3@addtoany.com",
    image: "http://dummyimage.com/138x100.png/cc0000/ffffff",
    password: "fO6)a6`kQ",
  },
  {
    name: "Carilyn Grzegorzewicz",
    email: "cgrzegorzewicz4@gravatar.com",
    image: "http://dummyimage.com/117x100.png/5fa2dd/ffffff",
    password: "qU2&&Mfd)0AMy8dR",
  },
  {
    name: "Arlana O' Brian",
    email: "ao5@nhs.uk",
    image: "http://dummyimage.com/207x100.png/5fa2dd/ffffff",
    password: "gK5}S%Iv",
  },
  {
    name: "Catie Postlethwaite",
    email: "cpostlethwaite6@craigslist.org",
    image: "http://dummyimage.com/137x100.png/5fa2dd/ffffff",
    password: "mG2<rsqT'=7jy),G",
  },
  {
    name: "Stephana Newton",
    email: "snewton7@dell.com",
    image: "http://dummyimage.com/180x100.png/cc0000/ffffff",
    password: "bF3@Ol6G2J/",
  },
  {
    name: "Jeramie Wisby",
    email: "jwisby8@state.gov",
    image: "http://dummyimage.com/211x100.png/cc0000/ffffff",
    password: "gL1,,e_)'Go&b",
  },
  {
    name: "Shirlee Gowenlock",
    email: "sgowenlock9@nature.com",
    image: "http://dummyimage.com/124x100.png/dddddd/000000",
    password: 'aQ8"<e(7',
  },
  {
    name: "Hunter Bussey",
    email: "hbusseya@prlog.org",
    image: "http://dummyimage.com/133x100.png/5fa2dd/ffffff",
    password: "lB3>b}fHm.z$IT9",
  },
  {
    name: "Maure Goch",
    email: "mgochb@naver.com",
    image: "http://dummyimage.com/219x100.png/dddddd/000000",
    password: "sW6)<?Yl=IlN~lYR",
  },
  {
    name: "Kip Coopey",
    email: "kcoopeyc@apache.org",
    image: "http://dummyimage.com/194x100.png/5fa2dd/ffffff",
    password: "fB4.5p!ko",
  },
  {
    name: "Gun Frantz",
    email: "gfrantzd@infoseek.co.jp",
    image: "http://dummyimage.com/154x100.png/ff4444/ffffff",
    password: "eA3/+@crp(5",
  },
  {
    name: "Katee McAllester",
    email: "kmcallestere@networksolutions.com",
    image: "http://dummyimage.com/183x100.png/cc0000/ffffff",
    password: "sQ7.IQ&ZuQ<",
  },
  {
    name: "Mab Vanyutin",
    email: "mvanyutinf@state.tx.us",
    image: "http://dummyimage.com/212x100.png/5fa2dd/ffffff",
    password: "bZ7=FPg/_A",
  },
  {
    name: "Sibella Durran",
    email: "sdurrang@bbb.org",
    image: "http://dummyimage.com/230x100.png/cc0000/ffffff",
    password: 'oB7$Op**oGN,8"qN',
  },
  {
    name: "Samantha Hamill",
    email: "shamillh@google.co.uk",
    image: "http://dummyimage.com/125x100.png/ff4444/ffffff",
    password: "gO5*,/OwQ",
  },
  {
    name: "Ham Dorning",
    email: "hdorningi@sitemeter.com",
    image: "http://dummyimage.com/175x100.png/5fa2dd/ffffff",
    password: "lN9@w8\\6?}k9}j",
  },
  {
    name: "Kelly Symones",
    email: "ksymonesj@washington.edu",
    image: "http://dummyimage.com/152x100.png/dddddd/000000",
    password: "kG4>gE5c*z84",
  },
  {
    name: "Christin Huxstep",
    email: "chuxstepk@slate.com",
    image: "http://dummyimage.com/211x100.png/ff4444/ffffff",
    password: "uO3&C*&7s!/+X6",
  },
  {
    name: "Kendell Sibbson",
    email: "ksibbsonl@ftc.gov",
    image: "http://dummyimage.com/135x100.png/dddddd/000000",
    password: "zT3~'Ra3",
  },
  {
    name: "Margo Hinksen",
    email: "mhinksenm@rakuten.co.jp",
    image: "http://dummyimage.com/133x100.png/ff4444/ffffff",
    password: "zI8{XzRP,rr",
  },
  {
    name: "Farley Gorelli",
    email: "fgorellin@free.fr",
    image: "http://dummyimage.com/187x100.png/dddddd/000000",
    password: "oE1?t1)x*n#(Gp",
  },
  {
    name: "Madelin Sharpling",
    email: "msharplingo@illinois.edu",
    image: "http://dummyimage.com/200x100.png/ff4444/ffffff",
    password: "uI0~J4(_|",
  },
  {
    name: "Etty Vaud",
    email: "evaudp@acquirethisname.com",
    image: "http://dummyimage.com/123x100.png/ff4444/ffffff",
    password: "mN3`W`ll",
  },
  {
    name: "Tracie O'Curran",
    email: "tocurranq@deviantart.com",
    image: "http://dummyimage.com/183x100.png/ff4444/ffffff",
    password: "mM5*l10eRvC*aQe",
  },
  {
    name: "Fanny Foye",
    email: "ffoyer@hatena.ne.jp",
    image: "http://dummyimage.com/224x100.png/ff4444/ffffff",
    password: 'gK5+=xZ"`jj',
  },
  {
    name: "Giusto Colbert",
    email: "gcolberts@walmart.com",
    image: "http://dummyimage.com/114x100.png/5fa2dd/ffffff",
    password: "aG8$@H8m'3.!l",
  },
  {
    name: "Larina Klimov",
    email: "lklimovt@typepad.com",
    image: "http://dummyimage.com/192x100.png/cc0000/ffffff",
    password: 'rQ7>sGo=q"x/',
  },
  {
    name: "Farleigh Willmott",
    email: "fwillmottu@berkeley.edu",
    image: "http://dummyimage.com/108x100.png/dddddd/000000",
    password: "fW5~k)/?BD",
  },
  {
    name: "Valina Kos",
    email: "vkosv@is.gd",
    image: "http://dummyimage.com/233x100.png/cc0000/ffffff",
    password: "jX2@GjcIx8E@",
  },
  {
    name: "Casie Botler",
    email: "cbotlerw@nbcnews.com",
    image: "http://dummyimage.com/237x100.png/ff4444/ffffff",
    password: "dE7%ii7h",
  },
  {
    name: "Philly Enoch",
    email: "penochx@devhub.com",
    image: "http://dummyimage.com/179x100.png/dddddd/000000",
    password: "iH7/.1ZdwIuX",
  },
  {
    name: "Ruggiero Hornig",
    email: "rhornigy@loc.gov",
    image: "http://dummyimage.com/137x100.png/5fa2dd/ffffff",
    password: "qI2`~@EPK",
  },
  {
    name: "Cindelyn Hawking",
    email: "chawkingz@eepurl.com",
    image: "http://dummyimage.com/193x100.png/ff4444/ffffff",
    password: "nO8/iFb0CC",
  },
  {
    name: "Harry Klosser",
    email: "hklosser10@cyberchimps.com",
    image: "http://dummyimage.com/131x100.png/dddddd/000000",
    password: 'oD7`%.wwaC3r"u',
  },
  {
    name: "Misha Jedrzaszkiewicz",
    email: "mjedrzaszkiewicz11@wsj.com",
    image: "http://dummyimage.com/188x100.png/ff4444/ffffff",
    password: "dP1=M*kk65,",
  },
  {
    name: "Aleece O'Donnell",
    email: "aodonnell12@acquirethisname.com",
    image: "http://dummyimage.com/232x100.png/cc0000/ffffff",
    password: "bJ9(i2da'4",
  },
  {
    name: "Katha Taw",
    email: "ktaw13@cyberchimps.com",
    image: "http://dummyimage.com/234x100.png/ff4444/ffffff",
    password: "bP7)/A|c6zyN#9U",
  },
  {
    name: "Delmor Stapforth",
    email: "dstapforth14@opera.com",
    image: "http://dummyimage.com/203x100.png/cc0000/ffffff",
    password: "dD3<D3Ok+rTPy",
  },
  {
    name: "Gabrielle Benoy",
    email: "gbenoy15@java.com",
    image: "http://dummyimage.com/248x100.png/ff4444/ffffff",
    password: "zP3>(E/z",
  },
  {
    name: "Hephzibah Drowsfield",
    email: "hdrowsfield16@1688.com",
    image: "http://dummyimage.com/207x100.png/ff4444/ffffff",
    password: 'dP3"p)4)Qfl',
  },
  {
    name: "Niel Rowden",
    email: "nrowden17@rakuten.co.jp",
    image: "http://dummyimage.com/238x100.png/ff4444/ffffff",
    password: "vL9,pOsG&fX?",
  },
  {
    name: "Bevvy Birrane",
    email: "bbirrane18@cisco.com",
    image: "http://dummyimage.com/223x100.png/5fa2dd/ffffff",
    password: "xL3%itm3",
  },
  {
    name: "Janel Liddiatt",
    email: "jliddiatt19@prnewswire.com",
    image: "http://dummyimage.com/138x100.png/5fa2dd/ffffff",
    password: "jM1_.'U%K$",
  },
  {
    name: "Dilan Spyby",
    email: "dspyby1a@cmu.edu",
    image: "http://dummyimage.com/219x100.png/dddddd/000000",
    password: "iJ3%q)WAfj0`",
  },
  {
    name: "Luca Davidwitz",
    email: "ldavidwitz1b@umich.edu",
    image: "http://dummyimage.com/177x100.png/cc0000/ffffff",
    password: "iF6+}LLUy.zY",
  },
  {
    name: "Alfredo Sager",
    email: "asager1c@state.tx.us",
    image: "http://dummyimage.com/216x100.png/dddddd/000000",
    password: "rC8}{TYH@p7)D",
  },
  {
    name: "Tam Mumford",
    email: "tmumford1d@nydailynews.com",
    image: "http://dummyimage.com/118x100.png/5fa2dd/ffffff",
    password: "eX8`,ie}T",
  },
  {
    name: "Bruno Elster",
    email: "belster1e@spotify.com",
    image: "http://dummyimage.com/156x100.png/ff4444/ffffff",
    password: "yS7+,WB5E",
  },
  {
    name: "Bobinette Wann",
    email: "bwann1f@alexa.com",
    image: "http://dummyimage.com/238x100.png/dddddd/000000",
    password: "qR9_h7ke",
  },
  {
    name: "Ettore Belone",
    email: "ebelone1g@networksolutions.com",
    image: "http://dummyimage.com/183x100.png/5fa2dd/ffffff",
    password: "rR0/cx*t",
  },
  {
    name: "Cathy Kelleway",
    email: "ckelleway1h@blogs.com",
    image: "http://dummyimage.com/229x100.png/dddddd/000000",
    password: "zE4=Ujxl6.VVo",
  },
  {
    name: "Hildegaard Tweedell",
    email: "htweedell1i@indiegogo.com",
    image: "http://dummyimage.com/140x100.png/dddddd/000000",
    password: "yK2&=Nx{3P/l#q",
  },
  {
    name: "Teodor Benes",
    email: "tbenes1j@shutterfly.com",
    image: "http://dummyimage.com/111x100.png/5fa2dd/ffffff",
    password: "fT9|3ogH=2",
  },
  {
    name: "Rina Scuse",
    email: "rscuse1k@indiatimes.com",
    image: "http://dummyimage.com/153x100.png/5fa2dd/ffffff",
    password: "rA0$oL0k8Jn",
  },
  {
    name: "Enrika Panks",
    email: "epanks1l@bravesites.com",
    image: "http://dummyimage.com/191x100.png/ff4444/ffffff",
    password: "uK5$e4i.",
  },
  {
    name: "Sascha Janous",
    email: "sjanous1m@cargocollective.com",
    image: "http://dummyimage.com/187x100.png/5fa2dd/ffffff",
    password: "tQ6|zR@T",
  },
  {
    name: "Margarette Grelka",
    email: "mgrelka1n@paypal.com",
    image: "http://dummyimage.com/246x100.png/ff4444/ffffff",
    password: "kS4'Hn80C",
  },
  {
    name: "Katherina Maskell",
    email: "kmaskell1o@illinois.edu",
    image: "http://dummyimage.com/150x100.png/5fa2dd/ffffff",
    password: "nF5?e<oCPo%m",
  },
  {
    name: "Andros Rheam",
    email: "arheam1p@china.com.cn",
    image: "http://dummyimage.com/230x100.png/cc0000/ffffff",
    password: "yL5,$b3,\\rDh",
  },
  {
    name: "Adolphus Ellerey",
    email: "aellerey1q@prweb.com",
    image: "http://dummyimage.com/223x100.png/ff4444/ffffff",
    password: "vB6'T4Ff.<)MLl",
  },
  {
    name: "Osborne Kennan",
    email: "okennan1r@nymag.com",
    image: "http://dummyimage.com/180x100.png/cc0000/ffffff",
    password: "pT1`w@WLzY16.R(j",
  },
  {
    name: "Aryn Giacubbo",
    email: "agiacubbo1s@skype.com",
    image: "http://dummyimage.com/199x100.png/cc0000/ffffff",
    password: "iP2|Zw<H<b}",
  },
  {
    name: "Frankie Dampier",
    email: "fdampier1t@kickstarter.com",
    image: "http://dummyimage.com/199x100.png/dddddd/000000",
    password: "eY3@I50DD%",
  },
  {
    name: "Waylen Bartram",
    email: "wbartram1u@yahoo.com",
    image: "http://dummyimage.com/205x100.png/5fa2dd/ffffff",
    password: "cU7`@|kO=mn=0'}E",
  },
  {
    name: "Kathrine Pincked",
    email: "kpincked1v@huffingtonpost.com",
    image: "http://dummyimage.com/153x100.png/cc0000/ffffff",
    password: "zH4=Hn1*",
  },
  {
    name: "Heida Perfect",
    email: "hperfect1w@wikipedia.org",
    image: "http://dummyimage.com/119x100.png/ff4444/ffffff",
    password: "xP8.zefw'tQ",
  },
  {
    name: "Martynne MacKellar",
    email: "mmackellar1x@wiley.com",
    image: "http://dummyimage.com/214x100.png/5fa2dd/ffffff",
    password: "uH2{j4i6uL8?|N59",
  },
  {
    name: "Kerrie Batchelour",
    email: "kbatchelour1y@engadget.com",
    image: "http://dummyimage.com/166x100.png/ff4444/ffffff",
    password: "dG9?W6_WpT9fXM",
  },
  {
    name: "Howard Maslen",
    email: "hmaslen1z@purevolume.com",
    image: "http://dummyimage.com/210x100.png/ff4444/ffffff",
    password: "vJ1}p/mP",
  },
  {
    name: "Alta Secret",
    email: "asecret20@hibu.com",
    image: "http://dummyimage.com/227x100.png/5fa2dd/ffffff",
    password: "bS7({*ZUkMh",
  },
  {
    name: "Stern Olenin",
    email: "solenin21@geocities.jp",
    image: "http://dummyimage.com/176x100.png/5fa2dd/ffffff",
    password: "pE7*egMKCqce0l'K",
  },
  {
    name: "Leena Tassell",
    email: "ltassell22@cdc.gov",
    image: "http://dummyimage.com/104x100.png/ff4444/ffffff",
    password: "kC7*s+jXxU",
  },
  {
    name: "Lisa Normanville",
    email: "lnormanville23@trellian.com",
    image: "http://dummyimage.com/208x100.png/5fa2dd/ffffff",
    password: "qH8$\\f@B5N",
  },
  {
    name: "Bili Glowacki",
    email: "bglowacki24@last.fm",
    image: "http://dummyimage.com/121x100.png/5fa2dd/ffffff",
    password: 'gW6\\@}>7)h"k',
  },
  {
    name: "Aurea Rawsen",
    email: "arawsen25@cocolog-nifty.com",
    image: "http://dummyimage.com/221x100.png/5fa2dd/ffffff",
    password: "zL5>v0o4+#7j7Uq",
  },
  {
    name: "Federica Myers",
    email: "fmyers26@vk.com",
    image: "http://dummyimage.com/156x100.png/cc0000/ffffff",
    password: "cC7$G6OirEiw$",
  },
  {
    name: "Rosalinde Braddon",
    email: "rbraddon27@gnu.org",
    image: "http://dummyimage.com/247x100.png/cc0000/ffffff",
    password: "uG9_Tik.",
  },
  {
    name: "Coletta Labbett",
    email: "clabbett28@unc.edu",
    image: "http://dummyimage.com/204x100.png/cc0000/ffffff",
    password: "tR5,7H7V/#)s+a|I",
  },
  {
    name: "Dore Renad",
    email: "drenad29@topsy.com",
    image: "http://dummyimage.com/113x100.png/ff4444/ffffff",
    password: "oP9@))>7=H",
  },
  {
    name: "Fiann Jeratt",
    email: "fjeratt2a@hatena.ne.jp",
    image: "http://dummyimage.com/131x100.png/cc0000/ffffff",
    password: "dU0#~j3s#Y",
  },
  {
    name: "Yolanda Caskie",
    email: "ycaskie2b@pagesperso-orange.fr",
    image: "http://dummyimage.com/119x100.png/ff4444/ffffff",
    password: "bD1!N_DXi",
  },
  {
    name: "Tammie Lorman",
    email: "tlorman2c@multiply.com",
    image: "http://dummyimage.com/150x100.png/dddddd/000000",
    password: "mT6$g|3t)\">~'}3M",
  },
  {
    name: "Estele Esel",
    email: "eesel2d@freewebs.com",
    image: "http://dummyimage.com/248x100.png/5fa2dd/ffffff",
    password: "uP8$46*o|/a`Z).",
  },
  {
    name: "Bernete Sambedge",
    email: "bsambedge2e@pen.io",
    image: "http://dummyimage.com/126x100.png/ff4444/ffffff",
    password: "fG6#Zv7{*`tB*(",
  },
  {
    name: "Starlene Maciaszczyk",
    email: "smaciaszczyk2f@sohu.com",
    image: "http://dummyimage.com/142x100.png/ff4444/ffffff",
    password: "fK4)`+Hv%rUmX.",
  },
  {
    name: "Putnam Abrami",
    email: "pabrami2g@github.io",
    image: "http://dummyimage.com/241x100.png/dddddd/000000",
    password: "zZ4@q2q/O3QdX",
  },
  {
    name: "Vin Penylton",
    email: "vpenylton2h@rediff.com",
    image: "http://dummyimage.com/137x100.png/dddddd/000000",
    password: "rD7,%==cfC(XEXs",
  },
  {
    name: "Florella Seczyk",
    email: "fseczyk2i@smugmug.com",
    image: "http://dummyimage.com/152x100.png/5fa2dd/ffffff",
    password: "vB2|!82?8+>nHe3",
  },
  {
    name: "Rainer Ordish",
    email: "rordish2j@state.tx.us",
    image: "http://dummyimage.com/223x100.png/dddddd/000000",
    password: "mZ6'g.cALew21x",
  },
  {
    name: "Annabel Plaschke",
    email: "aplaschke2k@foxnews.com",
    image: "http://dummyimage.com/127x100.png/cc0000/ffffff",
    password: "lT6{7B_`}",
  },
  {
    name: "Doreen Devo",
    email: "ddevo2l@oaic.gov.au",
    image: "http://dummyimage.com/207x100.png/cc0000/ffffff",
    password: "gE0~vGgX",
  },
  {
    name: "Laura O'Scanlan",
    email: "loscanlan2m@cbslocal.com",
    image: "http://dummyimage.com/241x100.png/ff4444/ffffff",
    password: "uO2*yZSO",
  },
  {
    name: "Jacquetta Cogdon",
    email: "jcogdon2n@last.fm",
    image: "http://dummyimage.com/226x100.png/dddddd/000000",
    password: "vF9%OOyqGqT@YejO",
  },
  {
    name: "Guenevere Bucktharp",
    email: "gbucktharp2o@pcworld.com",
    image: "http://dummyimage.com/232x100.png/cc0000/ffffff",
    password: "dE5{vTUB.Ooro/",
  },
  {
    name: "Vikki Turn",
    email: "vturn2p@webeden.co.uk",
    image: "http://dummyimage.com/114x100.png/5fa2dd/ffffff",
    password: "iK7.qVhT`yURM@Cc",
  },
  {
    name: "Isadora Meineking",
    email: "imeineking2q@techcrunch.com",
    image: "http://dummyimage.com/173x100.png/5fa2dd/ffffff",
    password: "iC2}*OA_M?=j",
  },
  {
    name: "Jolyn Cranstone",
    email: "jcranstone2r@ft.com",
    image: "http://dummyimage.com/240x100.png/cc0000/ffffff",
    password: "hJ7>mT/G1!VS@",
  },
];

export async function GET() {
  for (const seededUser of seededUsers) {
    //     const result = await authClient.admin.createUser({
    //       name: seededUser.name,
    //       email: seededUser.email,
    //       password: seededUser.password,
    //       role: "user",
    //       data: {
    //         image: seededUser.image,
    //       },
    //       fetchOptions: {
    //         headers: await headers(),
    //       },
    //     });
    console.log(seededUser);
  }

  return new Response("all created");
}
